language: objective-c
osx_image: xcode10.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - pod lib lint --allow-warnings

    - xcodebuild clean build -project QNDeviceSDKDemo.xcodeproj -scheme 'QNSDK' -configuration Debug
    - xcodebuild clean build -project QNDeviceSDKDemo.xcodeproj -scheme 'QNSDK' -configuration Release
    
after_success:
    - bash <(curl -s https://codecov.io/bash)